### ISSUE TITLE
Front-end updates

### ISSUE THREAD

**Issue by jackhkmatthews** [Rassibassi/doyoutrackid#3]
Hi RassiBassi,

I love the site you've created and would really like to contribute some time to the front-end.

I also have a friend who is a UX/UI designer and fellow Charlie Bones / Do!! You!!! fan who is also keen to contribute.

How would you feel about them spending some time redesigning the frontend (maintaining current functionality) and then me implementing these designs?

Thanks
Jack

**Comment by Rassibassi** [comment]
Sure, go wild :)

One request I have though, please do not implement any auto refresh, as I pay per request to the backend. For that reason, I also added an artificial waiting time during every backend request, such that one cannot spam the refresh button [1]. It would be cool to keep that as well, to ensure it's not going to cost me.

I just set the CORS origin to allow any `'*'` [2], such that you can request the backend from localhost:3000 :)

[1] https://github.com/Rassibassi/doyoutrackid/blob/5f0467b92a63cd7df4fd991af76a695e700ce159/frontend/src/App.js#L83
[2] https://github.com/Rassibassi/doyoutrackid/blob/5f0467b92a63cd7df4fd991af76a695e700ce159/backend/app.py#L48

**Comment by jackhkmatthews** [comment]
Hi Rassibassi,

Nice! In that case I'll post the designs here once they're complete (a few weeks) and then start submitting implementation PRs.

RE the request, sure, I'll maintain that functionality.

Thanks for updating CORS, will make local deving easier. I'll let you know if I have any other questions.

Thanks
Jack

**Comment by jackhkmatthews** [comment]
Hi RassiBassi,

My friend is more or less finished with the designs. They're quite strange but I really like them and hope you do too (there are some screenshots below).

I'm hoping to make a start building them before the new year and I'll let you know how I get on.

Merry Christmas
Jack

<img width="954" alt="Screenshot 2021-12-20 at 19 13 21" src="https://user-images.githubusercontent.com/20629455/146820276-d647e6a6-31f9-4049-8601-2c8886fd80c4.png">
<img width="954" alt="Screenshot 2021-12-20 at 19 13 30" src="https://user-images.githubusercontent.com/20629455/146820283-1aaf0405-505c-4e4b-af32-912d74143b05.png">
<img width="1006" alt="Screenshot 2021-12-20 at 19 13 43" src="https://user-images.githubusercontent.com/20629455/146820286-5e0e26c0-570d-4e12-a77b-73e3ea21510d.png">
<img width="886" alt="Screenshot 2021-12-20 at 19 13 54" src="https://user-images.githubusercontent.com/20629455/146820290-e68f68ea-620a-497f-9eb4-a1c8aa05eebd.png">

**Comment by Rassibassi** [comment]
great work, go ahead. let me know if you need anything from me
