### ISSUE TITLE
Eleven Eleven in GMT

### ISSUE THREAD

**Issue by jackhkmatthews** [Rassibassi/doyoutrackid#6]
As spotted by @Rassibassi , 11:11 mode was set for 11:11 => 11:12 in the client's local time zone.

This should be set to 11:11 => 11:12 GMT to match the radio show.

This should now be fixed. @Rassibassi lemme know if you get a chance to double check this 👍

**Comment by Rassibassi** [comment]
looks good, will try to test it tomorrow, just PR and Ill merge it tomorrow if it worked :)

**Comment by Rassibassi** [comment]
![image](https://user-images.githubusercontent.com/2855550/150112617-32fda023-6cef-4bf3-b82f-05a233f781bb.png)

Not sure how to solve this, but the little 11:11 link is displayed, although it's not 11:11 in the UK. Screenshot taken 11:28 copenhagen time :)

but it's also fine I guess.

**Comment by jackhkmatthews** [comment]
Hey, yeah that's expected behaviour, it's an easter egg, if you click on it you can enter 11:11 mode whenever
